apiVersion: v1
kind: Service
metadata:
    name: svc-aem
spec:
    type: NodePort
    ports:
      - port: 80
        nodePort: 30001
        targetPort: 5000
        protocol: TCP
    selector:
        app: aem