apiVersion: v1
kind: Service
metadata:
    name: svc-aem-ui-lb
spec:
    type: LoadBalancer
    ports:
      - port: 80
        nodePort: 30000
        targetPort: 80
    selector:
        app: aem-ui