name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create dummy file
        run: 'echo "Value of Test is :: ${Test}" >> dummy.txt && cat dummy.txt && ls'
      - name: Substitute env vars in files
        env:
          Test: "${{ secrets.DOCKERHUB_USERNAME }}"
        uses: chris-peterson/virgo@v1
        with:
          templates: "./Source/AEM/SPS.AEM.WEB/appsettings.json"
      - name: Display updated file content
        run: echo "$(<Source/AEM/SPS.AEM.WEB/appsettings.json)"
      

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_GRASS_036506100 }}
          action: "close"
